################
# Basic config
################

baseurl = "https://c74ce35e.ngrok.io"
languageCode = "pl"

################
# SEO config
################

enableRobotsTXT = true
DisableRSS = true # This is not a fucking blog

title = ""
[params]
description = "" # Suggested, controls default description meta

################
# Menu config
################

[[menu.main]]
name = "github"
weight = 1000
url = "https://github.com/hs3city"
