# Master config
baseurl = "https://c74ce35e.ngrok.io"
languageCode = "pl"
title = "hack3rspace"

# SEO config
enableRobotsTXT = true
DisableRSS = true
[params]
description = "" # Suggested, controls default description meta

# Minor config
show_menu = true
powered_by = true

################
# Noob editable
################

# Menu config
[[menu.main]]
name = "Start"
weight = 1
url = "/"

[[menu.main]]
name = "About"
weight = 2
url = "/page/about/"

[[menu.main]]
name = "Github"
weight = 1000
url = "https://github.com/hs3city"
