################
# Dev config
################

# Master config
baseurl = "https://c74ce35e.ngrok.io"
languageCode = "pl"
title = "hack3rspace"

# SEO config
enableRobotsTXT = true
DisableRSS = true
[params]
description = "" # Suggested, controls default description meta

# Minor config
show_menu = true

################
# Menu config
################

[[menu.main]]
name = "github"
weight = 1000
url = "https://github.com/hs3city"
