# Basics
#=================

baseurl = "https://c74ce35e.ngrok.io"
languageCode = "pl"

#=================
# Meta
#=================

title = ""
[params]
description = "" # Suggested, controls default description meta

#=================
# Dev
#=================

enableRobotsTXT = true
DisableRSS = true # This is not a fucking blog
enableGitInfo = true

#=================
# Menu

[[menu.main]]
name = "github"
weight = 1000
url = "https://github.com/hs3city"
